/**
 * Barrios oficiales del municipio de Cereté, Córdoba, Colombia.
 * Fuente: Plan Básico de Ordenamiento Territorial (PBOT) de Cereté 2012-2023.
 * Lista usada para estandarizar la localidad en el registro de usuarios
 * y evitar inconsistencias de escritura.
 */
export const LOCALIDADES_CERETE: string[] = [
  '11 de Noviembre',
  '20 de Enero',
  '24 de Mayo',
  '7 de Agosto',
  'Alfonso López',
  'Arenal',
  'Argelia',
  'Bienestar Social',
  'Botavén',
  'Caño Viejo',
  'Caracas',
  'Chuchurubí',
  'El Abanico',
  'El Bongo',
  'El Carmen',
  'El Cañito',
  'El Descanso',
  'El Jardín',
  'El Naranjo',
  'El Noval',
  'El Paraíso',
  'El Totumo',
  'Girasoles',
  'La Candelaria',
  'La Ceiba',
  'La Esperanza',
  'La Floresta',
  'La Florida',
  'Las Acacias',
  'Las Américas',
  'Las Lomas',
  'Las Mohosas',
  'Las Palmas',
  'Marralú',
  'Miraflores',
  'Morrocoy',
  'Orilla del Río',
  'Playa Rica',
  'Proleche',
  'Quemado',
  'Rabolargo',
  'San José',
  'San Miguel',
  'Santa Clara',
  'Santa María',
  'Santa Teresa',
  'Severá',
  'Sinaí',
  'Sincelejito',
  'Suteatro',
  'Terrón',
  'Valparaíso',
  'Venus',
  'Vilches',
  'Villa Celina',
];
